---
driver:
  name: vagrant

provisioner:
    name               : ansible_push
    verbose            : "vvvv"
    ansible_config     : "test/ansible.cfg"
    idempotency_test   : False
    sudo               : True
    #chef_bootstrap_url : False
    #extra_vars        : "@kitchen_vars.yml"

platforms:
    - name: Debian-jessie
      driver:
        box: debian/jessie64
        customize:
          memory: 128
    - name: Debian-wheezy
      driver:
        box: debian/wheezy64
        customize:
          memory: 128
    - name: Ubuntu-trusty
      driver:
        box: ubuntu/trusty64
        customize:
          memory: 128

suites:
  - name: supernode
    provisioner:
      playbook: "test/application/supernode.yml"
      extra_vars: {'kitchen_connection': 'smart'}
  - name: mapserver
    provisioner:
      playbook: "test/application/mapserver.yml"
      extra_vars: {'kitchen_connection': 'smart'}