---
driver:
  name: vagrant

provisioner:
    name               : ansible_push
    verbose            : "vvvv"
    ansible_config     : "test/ansible.cfg"
    idempotency_test   : False
    #chef_bootstrap_url : False
    #extra_vars        : "@kitchen_vars.yml"

platforms:
    - name: Debian-jessie
      driver:
        box: ARTACK/debian-jessie
    - name: Debian-7.8
      driver:
        box: chef/debian-7.8
    - name: Ubuntu-14.04
      driver:
        box: ubuntu/trusty64

suites:
  - name: supernode
    provisioner:
      playbook: "test/application/supernode.yml"
      extra_vars: {'kitchen_connection': 'smart'}
#  - name            : group
#    provisioner     :
#        playbook    : "test/application/group.yml"
#        extra_vars  : { 'kitchen_connection': 'smart' }