- src: https://github.com/ahelal/ansible-usermanage
  version: master
  name: usermanage
  path: galaxy-roles

- src: pdellaert.dhcp_server
  path: galaxy-roles

- src: debops.radvd
  path: galaxy-roles

- src: jdauphant.unbound
  path: galaxy-roles

- src: dereulenspiegel.fastd
  path: galaxy-roles

- src: dereulenspiegel.alfred
  path: galaxy-roles

- src: jdauphant.nginx
  path: galaxy-roles

- src: laggyluke.nodejs
  path: galaxy-roles