- hosts: supernodes:mapservers
  become: yes
  roles:
    - service-nginx
    - service-node_exporter

- hosts: serviceservers
  become: yes
  roles:
    - service-nginx
    - service-gogs
    - service-wiki
    - service-prometheus
