---

- hosts: all
  roles:
    - common-auth
    - common-net
    - common-system
    # - service-nginx
    # - service-node_exporter

- hosts: all:!supernodes
  roles:
    - common-ntpclient

- hosts: mesh
  roles:
    - mesh-routing
    - mesh-interfaces

- hosts: batman
  roles:
    - mesh-batman

- hosts: supernodes
  roles:
    - gateway-peering
    - gateway-nat
    - gateway-iptables
    - mesh-vpn-fastd
    - service-ntp
    - service-dns
    - service-dhcp

- hosts: mapservers
  roles:
    - service-nginx
    # - service-map

- hosts: images.ffdo.de
  roles:
    - service-nginx
    # - service-images

- hosts: build.ffdo.de
  roles:
    - common-docker

- hosts: services.ffdo.de
  roles:
    # - common-restic
    - service-nginx
    - service-gogs
    - service-wiki
    - service-prometheus
