---
# tasks file for peering

- name: Install interface definitions
  template:
    dest: "/etc/network/interfaces.d/{{item.file}}"
    src: "{{item.template}}"
  with_items:
  - file: peering.cfg
    template: peering_interfaces.j2

# - name: Install bird.conf
#   template: src=bird.conf.j2 dest=/etc/bird/conf.d/peering.conf
#   notify: Reload bird daemons

# - name: Install bird6.conf
#   template: src=bird6.conf.j2 dest=/etc/bird/conf6.d/peering.conf
#   notify: Reload bird daemons
