---
# handlers file for ff-supernode
# In Ubuntu restarting the networking service causes problems.
# So we use ifdown and ifup to enable changes
- name: Restart supervisor
  service: name=supervisor state=restarted

- name: Reboot machine
  shell: reboot

- name: Restart cron
  service: name=cron state=restarted