---
# tasks file for ffdo.mapserver-nginx

- name: Ensure nginx is installed
  apt: name=nginx state=present update_cache=yes cache_valid_time=3600

- name: Install nginx configs
  template:
    src: meshviewer.conf.j2
    dest: /etc/nginx/site-include/{{ ansible_fqdn }}/meshviewer.conf
  notify:
  - Reload nginx
