- include_vars: "{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml"

- name: Ensure Alfred build deps are installed
  apt: name={{item}} state=present
  with_items: "{{alfred_build_deps}}"