---
galaxy_info:
  author: Till Klocke
  description: Creates a map server to visualize the mesh of a Freifunk Community
  company: Freifunk Dortmund
  license: MIT
  min_ansible_version: 1.2
  platforms:
  - name: Ubuntu
    versions:
    - all
  - name: Debian
    versions:
    - all
  categories:
  - monitoring
  - networking
  - system
  - web
dependencies:
- batman
- mapserver-certificates
- role: jdauphant.nginx
  nginx_sites:
    default:
    - listen 80 default_server
    - "listen [::]:80 default_server"
    - server_name _
    - listen 443 ssl
    - "listen [::]:443 ssl"
    - "ssl_certificate /etc/nginx/ssl/wiki.ffdo.de.crt"
    - "ssl_certificate_key /etc/nginx/ssl/wiki.ffdo.de.key"
    - "ssl_dhparam /etc/nginx/dhparams.pem"
    - "root /var/www"
    - index index.html
    - "location = / { return 302 /meshviewer/; }"
    - location /meshviewer {
                alias {{meshviewer_install_directory}};
                try_files $uri $uri/ =404;
                gzip on;
                gzip_comp_level 2;
                gzip_types application/json application/javascript text/css;
                gzip_vary on;
        }
    - location /data {
                alias {{ffmap_backend_data_dir}};
                gzip on;
                gzip_comp_level 2;
                gzip_types application/json;
                gzip_vary on;
        }
- meshviewer
- supernode-interfaces
