---
galaxy_info:
  author: Till Klocke
  description: Creates a map server to visualize the mesh of a Freifunk Community
  company: Freifunk Dortmund
  license: MIT
  min_ansible_version: 1.2
  platforms:
  - name: Ubuntu
    versions:
    - all
  - name: Debian
    versions:
    - all
  categories:
  - monitoring
  - networking
  - system
  - web
dependencies:
- batman
- jdauphant.nginx
- meshviewer
- supernode-interfaces
