---
# tasks file for ffdo.bird

- name: Ensure bird routing daemon is installed
  apt: name=bird state=present update_cache=yes cache_valid_time=3600

- name: Ensure bird config dir exists
  file: name={{bird_config_dir}} state=directory

- name: Ensure bird include dirs exists
  file: name={{bird_config_dir}}/{{item}} state=directory
  with_items:
    - conf.d
    - conf6.d

- name: Install bird.conf
  template: src=bird.conf.j2 dest={{bird_config_dir}}/bird.conf
  notify: Reload bird daemons

- name: Install bird6.conf
  template: src=bird6.conf.j2 dest={{bird_config_dir}}/bird6.conf
  notify: Reload bird daemons

- name: Enable and start bird and bird6
  service: name={{item}} state=started enabled=yes
  with_items:
    - bird
    - bird6