---
galaxy_info:
  author: Till Klocke
  description: Installs ffmap-backend
  company: Freifunk Dortmund
  license: MIT
  min_ansible_version: 1.2
  platforms:
  - name: Debian
    versions:
    - all
  categories:
  - monitoring
  - networking
dependencies:
- alfred
- alfred-json
