---
# tasks file for map-server
- include_vars: "{{ ansible_os_family }}.yml"

- name: Install necessary packages
  apt: name={{item}} state=present
  with_items: "{{mapserver_packages}}"

- name: Create supervisor services
  when: supervisor_services is defined
  template: src=supervisor.service.j2 dest=/etc/supervisor/conf.d/{{item.name}}.conf
  with_items: "{{supervisor_services}}"
  notify: Restart supervisor

- name: Ensure supervisor is started and enabled
  service: name=supervisor state=started enabled=yes