---
- name: Install systemd services
  template: src={{item}}.service.j2 dest=/etc/systemd/system/{{item}}.service
  with_items:
  - alfred
  - batadv-vis

- name: Enable and start systemd services
  service: name={{item}} enabled=yes state=started
  with_items:
  - alfred
  - batadv-vis
