- name: Install fastd build dependencies
  when: not repo_universe_factory_available
  apt: name={{item}} update_cache=yes
  with_items:
    - libcap2
    - libcap-dev
    - bison
    - pkg-config
    - cmake
    - libssl1.0.0
    - libssl-dev
    - git
    - build-essential

- include: source.yml
  when: not repo_universe_factory_available

- name: Install fastd via Apt
  when: repo_universe_factory_available
  apt: name=fastd state=latest