- name: Restart gogs
  service:
    name: gogs
    state: restarted

- name: Reload nginx
  service:
    name: nginx
    state: reloaded

- name: Restart nginx
  service:
    name: nginx
    state: restarted
