- name: Make sure necessary tools are installed
  apt: name={{item}} state=present
  with_items:
  - wget
  - supervisor
  - ntp

- name: Remove resolvconf from Ubunut
  apt: name=resolvconf state=absent

- name: Install backport kernel for Debian wheezy
  apt: name=linux-image-amd64 default_release=wheezy-backports state=latest
  when: ansible_distribution_release == 'wheezy'
  notify: Reboot machine

- name: Start and enable supervisor
  service: name=supervisor state=started enabled=yes