---
# tasks file for ff-supernode

- include: debian.yml
  when: ansible_distribution == 'Debian'

- include: debian.yml
  when: ansible_distribution == 'Ubuntu'

- name: Install crontab to update the blacklist
  cron:
    name: Update blacklist
    minute: '*/5'
    job: wget -q -O /etc/fastd/fastd-blacklist.json https://raw.githubusercontent.com/ffruhr/fastdbl/master/fastd-blacklist.json

- name: Install verify shell script
  template: src=fastd-blacklist.sh.j2 dest=/etc/fastd/fastd-blacklist.sh mode="u=rwx,g=rx,o=r"

- name: Create supervisor services
  template: src=supervisor.service.j2 dest=/etc/supervisor/conf.d/{{item.name}}.conf
  with_items: "{{supervisor_services}}"
  notify: Restart supervisor

- name: Install ntp.conf
  template: src=ntp.conf.j2 dest=/etc/ntp.conf