---
# tasks file for ff-supernode

- include: debian.yml
  when: ansible_distribution == 'Debian'

- include: debian.yml
  when: ansible_distribution == 'Ubuntu'

- name: Install crontab to update the blacklist
  cron:
    name: Update blacklist
    minute: '*/5'
    job: wget -q -O /etc/fastd/fastd-blacklist.json https://raw.githubusercontent.com/ffruhr/fastdbl/master/fastd-blacklist.json

- name: Install verify shell script
  template: src=fastd-blacklist.sh.j2 dest=/etc/fastd/fastd-blacklist.sh mode="u=rwx,g=rx,o=r"

- name: Create supervisor services
  template: src=supervisor.service.j2 dest=/etc/supervisor/conf.d/{{item.name}}.conf
  with_items: "{{supervisor_services}}"
  notify: Restart supervisor

- name: Install ntp.conf
  template: src=ntp.conf.j2 dest=/etc/ntp.conf

- name: Install python dependencies for ffrl tools
  pip: name={{item}} executable=pip3
  with_items:
  - pyroute2

- name: Create install dir for ffrl tools
  file: dest={{supernode_freifunk_tools_dir}} state= directory

- name: Clone ffrl tools
  git: repo={{supernode_freifunk_tools_repo}} dest={{supernode_freifunk_tools_dir}}

- name: Install nodeinfo cron job
  cron: 
    name: nodeinfo.py 
    job: "{{supernode_freifunk_tools_dir}}/nodeinfo/nodeinfo.py | gzip | alfred -s 158"
    user: root