---

- name: Install fastd via Apt
  apt: name=fastd state=latest default_release={{ ansible_distribution_release }}-backports

- name: Add fastd user
  user: name=fastd system=yes home=/etc/fastd createhome=no

- name: Create fastd config directories
  file: path=/etc/fastd/{{item.name}}/dummy state=directory
  with_items: "{{fastd_instances}}"

- name: Create fastd configs
  template: src=fastd.conf.j2 dest=/etc/fastd/{{item.name}}/fastd.conf
  with_items: "{{fastd_instances}}"
  notify: Restart fastd

- name: Create fastd secrets
  template: src=secret.conf.j2 dest=/etc/fastd/{{item.name}}/secret.conf
  with_items: "{{fastd_instances}}"
  notify: Restart fastd

- name: Ensure fastd is enabled
  service: name=fastd enabled=yes
  notify: Restart fastd
