---
# tasks file for test-uplink

- name: Install interfaces config
  template: src=interfaces.j2 dest=/etc/network/interfaces
  notify: Restart network

- name: Install necessary packages
  apt: name={{item}} state=present
  with_items:
  - bird
  - openvpn
