- name: Remove resolvconf from Ubunut
  when: ansible_distribution == 'Ubuntu'
  apt: name=resolvconf state=absent

- name: Install custom resolv.conf
  template: src=resolv.conf.j2 dest=/etc/resolv.conf

- name: Make sure necessary tools are installed
  apt: name={{item}} state=present
  with_items:
  - wget
  - ntp
  - git

- name: Install dependencies for ffrl tools
  apt: name={{item}}
  with_items:
  - python3
  - python3-pip

- name: Install backport kernel for Debian wheezy
  apt: name=linux-image-amd64 default_release=wheezy-backports state=latest
  when: ansible_distribution_release == 'wheezy'
  notify: Reboot machine

- name: Start and enable supervisor
  service: name=supervisor state=started enabled=yes