- name: Install fastd build dependencies
  when: not repo_universe_factory_available
  apt: name={{item}} update_cache=yes
  with_items:
    - libcap2
    - libcap-dev
    - bison
    - pkg-config
    - cmake
    - libssl1.0.0
    - libssl-dev
    - git
    - build-essential

- name: Install rng-tools
  apt: name=rng-tools state=present

- name: Make sure that rng-tools uses /dev/urandom
  lineinfile:
    dest: /etc/default/rng-tools
    line: HRNGDEVICE=/dev/urandom

- include: source.yml
  when: not repo_universe_factory_available

- name: Install fastd via Apt
  when: repo_universe_factory_available
  apt: name=fastd state=latest

- name: Add fastd user
  user: createhome=no system=yes shell={{fastd_user_shell}} name={{fastd_user_name}}