---
galaxy_info:
  author: Till Klocke
  description: Installs and configures bird routing daemon
  company: Freifunk Dortmund
  license: MIT
  min_ansible_version: 1.2
  platforms:
  - name: Ubuntu
    versions:
    - all
  - name: Debian
    versions:
    - all
  categories:
  - networking
dependencies: []