---
- name: ensure acmetool is installed
  apt: name=acmetool install_recommends=no state=latest default_release={{ ansible_distribution_release }}-backports

- name: Ensure acmetool response file is up to date
  register: responsefile
  template: 
    src: acme_config.j2
    dest: /var/lib/acme/responses.yml

- name: Setup acmetool
  when: responsefile|changed
  shell: /usr/bin/acmetool quickstart --batch --response-file=/var/lib/acme/responses.yml
