---
- name: ensure acmetool repository key is installed
  apt_key:
    id: EDB58DFA
    data: "{{ lookup('file', 'acmetool.gpg') }}"

- name: ensure acmetool apt repository is installed
  apt_repository: repo='deb http://ppa.launchpad.net/hlandau/rhea/ubuntu xenial main'

- name: ensure acmetool is installed
  apt: name=acmetool install_recommends=no

- name: Ensure acmetool config is up to date
  template: 
    src: acme_config.j2
    dest: /var/lib/acme/conf/target

- name: Ensure acmetool cronjob is installed
  cron:
    name: "Renew Let's Encrypt certificates"
    job: /usr/bin/acmetool --batch reconcile
    hour: 3
    minute: 30
    day: 1

