- include_vars: "{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml"

- name: Ensure Alfred build deps are installed
  apt: name={{item}} state=present
  with_items: "{{alfred_build_deps}}"

- name: Ensure alfred-gpsd build deps are installed
  when: alfred_gps
  apt: name={{item}} state=present
  with_items: "{{alfred_gpsd_build_deps}}"

- name: Ensure that debugfs is mounted. Alfred seems to depend on it
  when: ansible_distribution_release == 'wheezy'
  lineinfile: dest=/etc/fstab line="none /sys/kernel/debug     debugfs   defaults   0  0"
  notify: Mount all