---
# tasks file for supernode-interfaces

- include: debian.yml
  when: ansible_distribution == 'Debian'

- include: debian.yml
  when: ansible_distribution == 'Ubuntu'

- name: Install bird.conf
  template: src=bird.conf.j2 dest={{bird_config_dir}}/bird.conf
  notify: Restart bird daemons

- name: Install bird6.conf
  template: src=bird6.conf.j2 dest={{bird_config_dir}}/bird6.conf
  notify: Restart bird daemons